services:
  localllm:
    image: vllm/vllm-openai:latest  # 192.168.161.132:5000/
    container_name: vllm
    ports:
      - "8106:8106"
    volumes:
      - ../_huggingface:/root/.cache/huggingface
      - ./:/app
    working_dir: /app
    #entrypoint: ["sleep", "infinity"]
    entrypoint:  ["bash", "vllm_serve.sh", "1"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # (選填) 有些舊版 Image 需要這行
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility # (選填) 確保能跑 CUDA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'          # 使用 1 張 GPU，若要用全部可改為 'all'
              capabilities: [gpu]

  deid:
    image: deid:v0  # 192.168.161.132:5000/
    container_name: deid
    working_dir: /app
    ports:
      - "8006:8006"
    environment:
      VLLM_CHAT_BASE_URL: http://vllm:8106/v1
      API_KEYS_PATH: /app/cfgs/api_keys.yaml
    volumes:
      - ./:/app
    command: "bash /app/env.sh"
