services:
  localllm:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11436:11434"
    volumes:
      - ../_ollama:/root/.ollama
    command: ["serve"]

  deidentification:
    image: deid:v0
    container_name: deid
    working_dir: /app
    ports:
      - "8006:8006"
    environment:
      OLLAMA_CHAT_BASE_URL: http://ollama:11434
      API_KEYS_PATH: /app/cfgs/api_keys.yaml
    volumes:
      - ./:/app
    command: "bash /app/env.sh"
